id: P000062
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །ཕ་དམ་པ་སངས་རྒྱས་ཀྱི་འདའ་ཀ་ཞལ་ཆེམས་དིང་རི་བརྒྱ་རྩ་མ་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ཕ་དམ་པ་སངས་རྒྱས།
  layers:
  - book_title
  - author
  - chapter_title
  id: LS-ZHI-04
web_metadata:
  title:
    en: The Hundred Verses of Dingri:Padampa Sangye’s Parinirvāṇa Testament
    bo: ཕ་དམ་པ་སངས་རྒྱས་ཀྱི་འདའ་ཀ་ཞལ་ཆེམས་དིང་རི་བརྒྱ་རྩ་མ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Zhije Series–  Book 4
    bo: ཞི་བྱེད།–  དེབ། ༤
  author:
    en: Padampa Sangye
    bo: ཕ་དམ་པ་སངས་རྒྱས།
  pusblisher:
    en: Dingri Langkor Zhijed Ling
    bo: དིང་རི་གླང་སྐོར་ཞི་བྱེད་གླིང་།
  sku: LS-ZHI-04
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: LS-ZHI-04.epub
  description:
    en: ''
    bo: ''
